### ISSUE TITLE
Cannot use 0.9.3 from maven central

### ISSUE THREAD

**Issue by angelozerr** [ralfstx/minimal-json#48]
Perhaps it's my fault, but I have changes my pom with 0.9.3:

```xml
<dependency>
	<groupId>com.eclipsesource.minimal-json</groupId>
	<artifactId>minimal-json</artifactId>
	<version>0.9.3</version>
</dependency
```

, and I have the following errors : 

```
[ERROR] Failed to execute goal on project _a: Could not resolve dependencies for project __a:_a:jar:0.0.1-SNAPSHOT: 
Failed to collect dependencies at com.eclipsesource.minimal-json:minimal-json:jar:0.9.3: Failed to read artifact descriptor for com.eclipsesource.minimal-json:minimal-json:jar:0.9.3: 
Could not find artifact com.eclipsesource.minimal-json:parent:pom:0.9.3 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```

Any help are welcome, thanks!

**Comment by sbandara** [comment]
I also get a build failure in one of my projects for the same dependency declaration, although the error looks slightly different, see "dev" branch at  https://travis-ci.org/sbandara/cloud-pokes

The good news is that builds against the previous release appear to be still intact, at least in my tests.

**Comment by ralfstx** [comment]
Thanks, I'll look into it. I've used the maven-release-plugin for the first time, chances are that I've messed up something.

**Comment by laurakolker** [comment]
I'm having the same error. Both with repositories http://repo.maven.apache.org/maven2 and https://repo1.maven.org/maven2 . In both cases it seems the pom downloads fine, but can't get to the downloading the JAR step, presumably because it can't find the referenced parent.

Here's what that looks like in the console:
```
Downloading: https://repo1.maven.org/maven2/com/eclipsesource/minimal-json/minimal-json/0.9.3/minimal-json-0.9.3.pom
Downloaded: https://repo1.maven.org/maven2/com/eclipsesource/minimal-json/minimal-json/0.9.3/minimal-json-0.9.3.pom (6 KB at 3.3 KB/sec)
Downloading: https://repo1.maven.org/maven2/com/eclipsesource/minimal-json/parent/0.9.3/parent-0.9.3.pom
... (truncated for readability)
[ERROR] Failed to execute goal on project c40-communication-tools: Could not resolve dependencies for project net.artemissoftware.confluence.plugins.collaboration:c40-communication-tools:atlassian-plugin:1.0-SNAPSHOT: Failed to collect dependencies at com.eclipsesource.minimal-json:minimal-json:jar:0.9.3: Failed to read artifact descriptor for com.eclipsesource.minimal-json:minimal-json:jar:0.9.3: Could not find artifact com.eclipsesource.minimal-json:parent:pom:0.9.3 in central (https://repo1.maven.org/maven2) -> [Help 1]
```
You can see that the pom is downloaded in the 2nd line, but then it goes hunting for "parent-0.9.3.pom" and can't find it.

I'm a little fuzzy on the way parent artifacts are declared, but is it possible that the name of the parent artifact in the pom doesn't reflect what you're intending? Or that the parent pom isn't actually there?
```
  <parent>
    <groupId>com.eclipsesource.minimal-json</groupId>
    <artifactId>parent</artifactId>
    <version>0.9.3</version>
  </parent>
```

**Comment by ralfstx** [comment]
Actually, the only purpose of this parent pom is to allow building and testing both modules in this repository in a single step from the repo root. Only the minimal-json module is published on Maven Central. In order to use the maven release plug-in I made some structural changes that included the parent pom in the dependency chain, something I didn't expect.

It was my mistake not to try installing from the prepared repository before publishing it. I was not aware of this risk. Sorry for that.

So, unfortunately, this version is now broken on Maven Central, and I'm afraid there's nothing I can do about it except getting a fixed 0.9.4 out as soon as possible.

**Comment by ralfstx** [comment]
From https://github.com/ralfstx/minimal-json/issues/55#issuecomment-112490753:

> Perhaps this will help in the meantime https://jitpack.io/#ralfstx/minimal-json/0.9.3

**Comment by ralfstx** [comment]
The workaround provided by @jitpack-io seems to work:

```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>com.github.ralfstx</groupId>
    <artifactId>minimal-json</artifactId>
    <version>0.9.3</version>
  </dependency>
</dependencies>
```

That may also be a nice way to consume snapshots.

**Comment by laurakolker** [comment]
Works like a charm. Thanks!

**Comment by tomasz** [comment]
We can't declare the `minimal-json` dependency using Maven central because this way:

	<dependencies>
		<dependency>
			<groupId>com.eclipsesource.minimal-json</groupId>
			<artifactId>minimal-json</artifactId>
			<version>0.9.3</version>
		</dependency>
	</dependencies>

because its packaging is declared as a `bundle` and not as the default `jar` vide: https://github.com/ralfstx/minimal-json/blob/master/com.eclipsesource.json/pom.xml#L12

Adding an additional attribute `<type>bundle</type>` to my `<dependency>` fixes things.

Is there a reason for packaging this as a `bundle`?

**Comment by thjaeckle** [comment]
Is there a workaround for using 0.9.3 from maven central? Unfortunately adding another repository is not an option for me :/
Would love to use the "merging" feature of 0.9.3 :)

**Comment by pacher** [comment]
+1 Please don't give up on maven central just because jitpack seems to work

**Comment by ralfstx** [comment]
@pacher I won't give up, but I'm afraid I don't have a solution for 0.9.3. However, 0.9.4 will be out very soon and I'll double check releases on maven central before flipping the switch from now on.

**Comment by pacher** [comment]
@ralfstx Thanks a lot.

**Comment by kristian** [comment]
@ralfstx Any update for 0.9.4, I am also struggeling with the parent POM not found...? Thanks

**Comment by ralfstx** [comment]
@kristian I plan to release 0.9.4 next Sunday (2015-07-19).

**Comment by kristian** [comment]
@ralfstx Looking forward to it. Thanks a lot. Greetings to Karlsruhe from Waghäusel ;-)
